#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    bootstrap_before = 'myspacevim#before'
    bootstrap_after = 'myspacevim#after'
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "slant"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    autocomplete_method = "coc"
    # Disable neomake:
    enable_neomake = false
    # Enable ale for checking:
    enable_ale = true
    filemanager = 'defx'
    disabled_plugins = ["vnote"]


# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = 'core#statusline'
  enable_statusline_bfpath = true

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 21

[[layers]]
  name = "lang#toml"

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "autocomplete"

[[layers]]
  name = "checkers"

[[layers]]
name = "ctrlp"

[[layers]]
  name = "debug"

[[layers]]
name = "default"

[[layers]]
name = "fzf"

[[layers]]
  name = "git"
  git-plugin = "fugitive"

[[layers]]
  name = "VersionControl"
  enable-gtm-status = true

[[layers]]
  name = "github"

[[layers]]
  name = "tools"

[[layers]]
  name = "tmux"

[[layers]]
  name = "test"

[[layers]]
  name = "sudo"

[[layers]]
  name = "lang#vim"

[[layers]]
  name = "lang#typescript"

[[layers]]
  name = "lang#ruby"

[[layers]]
  name = "lang#python"

[[layers]]
  name = "unite"

[[layers]]
  name = "lang#extra"

[[layers]]
  name = "lang#csharp"

[[layers]]
  name = "lang#rust"

[[layers]]
  name = "lang#html"
  [user_emmet_settings]
  leader_key = "<C-Y>"
  [user_emmet_settings."javascript.jsx"]
  extends = "jsx"


[[custom_plugins]]
  repo = "https://gitlab.com/dbeniamine/todo.txt-vim"
  merged = false
[[custom_plugins]]
  repo = "kovetskiy/sxhkd-vim"
  merged = false
[[custom_plugins]]
  repo = "liuchengxu/vista.vim"
  merged = false
# [[custom_plugins]]
  # repo = "michal-h21/vim-zettel"
  # merged = false
[[custom_plugins]]
  repo = "vimwiki/vimwiki"
  merged = false
[[custom_plugins]]
  repo = "junegunn/fzf.vim"
  merged = false
[[custom_plugins]]
  repo = "aarleks/zettel.vim"
  merged = false
[[custom_plugins]]
  repo = "dbeniamine/cheat.sh-vim"
  merged = false
[[custom_plugins]]
  repo = "wlemuel/vim-tldr"
  merged = false
