#!/usr/bin/env bash

# run the xrandr command if an external monitor is connected to the
# laptop.  This must be executed before the polybar command, so that
# polybar can set the two separate bars properly.
if [ -x /mnt/Data/bspwm_laptop_dual_monitor ];then
    bspwm_laptop_dual_monitor
fi

if [[ -x /usr/bin/polybar ]]; then
  bash $HOME/.config/polybar/launch-polybar.sh
fi

#================================================================================
#                                launch everytime
#================================================================================

# Appearance and keyboard:
nitrogen --restore &
sleep 1; 
xrdb --merge ~/.Xresoureces;
sleep 1;
wal -R -n;
sleep 1;
setxkbmap -layout us,ru -option 'grp:shifts_toggle,lv3:ralt_switch,misc:typo' &

# Set volume to 30%
amixer -q sset Master 30%

# Gnome services:
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & eval $(gnome-keyring-daemon -s --components=pkcs11,secrets,ssh,gpg) &
/usr/libexec/gnome-settings-daemon-localeexec &
dconf write /org/gnome/settings-daemon/plugins/cursor/active false &
setwac-run &
# /usr/lib/geoclue-2.0/demos/agent &
killall dropdown_todo && /mnt/Data/Scripts/todo_today.sh &

#================================================================================
#                             Launch only at startup
#================================================================================

# TODO: add a function for operate on pgrep and run
function run_process() {
  pgrep -u $USER "$1" >/dev/null || "$2" &
}

function run_process_test() {
  pgrep -u $USER "$1" >/dev/null || notify-send "$2"
}
# WORKAROUND: Commands with spaces hasnt passed as full string to function
pgrep -u $USER compton || compton -b --config ~/.config/compton/compton.conf &

# Add programm name and launch cmd to the associative array:
declare -A PROCESSES
PROCESSES[gnome-screensaver]="gnome-screensaver"
# Launch composite manager:
PROCESSES[compton]="compton -b --config ~/.config/compton/compton.conf"
# Mount disks daemon:
PROCESSES[udiskie]="udiskie"
# Bluetooth manager:
PROCESSES[blueman-applet]="blueman-applet"
# Night light:
PROCESSES[redshift-gtk]="redshift-gtk"
# Keybindings daemon:
PROCESSES[sxhkd]="sxhkd"
# Synthing:
#PROCESSES[syncthingtray]="syncthingtray --wait"
# Clipboard:
PROCESSES[copyq]="copyq"
# Launcher:
PROCESSES[albert]="albert"
# Clouds:
#PROCESSES[dropbox]="dropbox start"
PROCESSES[megasync]="megasync"
PROCESSES[pcloud]="pcloud"
# Telegram:
PROCESSES[telegram]="telegram-desktop"
# Networks manager:
PROCESSES[nm-applet]="nm-applet"
# Torrent client:
PROCESSES[qbittorrent]="qbittorrent"
# Hide mouse after 3s:
# PROCESSES[unclutter]="unclutter --timeout 3"
pgrep -u $USER unclutter >/dev/null || unclutter --timeout 5 &  
# Update-checker:
PROCESSES[update-checker]="update-checker"

pgrep -u $USER syncthingtray || syncthingtray --wait &
pgrep -u $USER dropbox || dropbox start &

for key in "${!PROCESSES[@]}" ; do
  pgrep -u $USER "$key" >/dev/null || "${PROCESSES[$key]}" &  
done

