#!/usr/bin/env bash

$HOME/.config/polybar/launch-polybar.sh
#================================================================================
#                             Launch only at startup
#================================================================================

# TODO: add a function for operate on pgrep and run
function run_process() {
  pgrep -u $USER "$1" >/dev/null || "$2" &
}

function run_process_test() {
  pgrep -u $USER "$1" >/dev/null || notify-send "$2"
}
# WORKAROUND: Commands with spaces hasnt passed as full string to function
compton -b --config ~/.config/compton/compton.conf &
syncthingtray --wait &
dropbox start &

# Add programm name and launch cmd to the associative array:
declare -A PROCESSES
# Launch composite manager:
PROCESSES[compton]="compton -b --config ~/.config/compton/compton.conf"
# Night light:
PROCESSES[redshift-gtk]="redshift-gtk"
# Keybindings daemon:
PROCESSES[sxhkd]="sxhkd"
# Synthing:
PROCESSES[syncthingtray]="syncthingtray --wait"
# Clipboard:
PROCESSES[copyq]="copyq"
# Launcher:
PROCESSES[albert]="albert"
# Bluetooth manager:
PROCESSES[blueman-applet]="blueman-applet"
# Clouds:
PROCESSES[dropbox]="dropbox start"
PROCESSES[megasync]="megasync"
PROCESSES[pcloud]="pcloud"
# Telegram:
PROCESSES[telegram]="telegram-desktop"
# Networks manager:
PROCESSES[nm-applet]="nm-applet"
# Torrent client:
PROCESSES[qbittorrent]="qbittorrent"
# Hide mouse after 3s:
PROCESSES[unclutter]="unclutter --timeout 3"
# Mount disks daemon:
PROCESSES[udiskie]="udiskie"

for key in "${!PROCESSES[@]}" ; do
  run_process "$key" "${PROCESSES[$key]}"
done

#================================================================================
#                                launch everytime
#================================================================================

# Appearance and keyboard:
nitrogen --restore; sleep 1; 
xrdb --merge ~/.Xresoureces;
sleep 1;
wal -R -n;
sleep 1;
setxkbmap -layout us,ru -option 'grp:shifts_toggle,lv3:ralt_switch,misc:typo' &

# Set volume to 30%
amixer -q sset Master 30%

# Gnome services:
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & eval $(gnome-keyring-daemon -s --components=pkcs11,secrets,ssh,gpg) &
/usr/libexec/gnome-settings-daemon-localeexec &
dconf write /org/gnome/settings-daemon/plugins/cursor/active false &
setwac-run &
# /usr/lib/geoclue-2.0/demos/agent &
killall dropdown_todo && /mnt/Data/Scripts/todo_today.sh &
