#!/bin/sh
# Clear all rules:
bspc rule -r "*"

bspc monitor HDMI1 -d 1 2 3 4 5 0
bspc monitor eDP1 -d 6 7

# autostart

###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier lock
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color	"4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#406ea5"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color "#dd2727"

###---Monitor And Desktop Settings----###
bspc config top_padding 24
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 4
bspc config window_gap 10

# Autostart:
killall redshift-gtk;
killall sxhkd;
killall compton;
killall syncthingtray;
killall copyq;
killall albert;
sleep 0.5
xrdb --merge ~/.Xresoureces &
wal -R -n &
sxhkd &
blueman-applet &
gnome-settings-daemon &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & eval $(gnome-keyring-daemon -s --components=pkcs11,secrets,ssh,gpg) &
setxkbmap -option 'grp:shifts_toggle,lv3:ralt_switch,misc:typo' &
nitrogen --restore; sleep 1; compton -b --config ~/.config/compton/compton.conf &
$HOME/.config/polybar/launch-polybar.sh
setwac-run &
udiskie &
dropbox start &
megasync &
pcloud &
telegram-desktop &
unclutter --timeout 3 &
nm-applet &
syncthingtray --wait &
/mnt/Data/Scripts/todo_today.sh &
copyq &
albert &
/usr/lib/geoclue-2.0/demos/agent &
redshift-gtk &
qbittorrent &
/usr/libexec/gnome-settings-daemon-localeexec &
dconf write /org/gnome/settings-daemon/plugins/cursor/active false &

# Dektops:
bspc desktop -n "primary"
bspc desktop -n "plan"
bspc desktop -n "code"
bspc desktop -n "browse"
bspc desktop -n "conf"
bspc desktop -n "media"
bspc desktop -n "chat"
bspc desktop -n "8"
bspc desktop -n "9"
bspc desktop -n  "10"

# Window rules:
bspc rule -a albert state=floating manage=on layer=above border=off center
bspc rule -a MEGAsync state=floating manage=on layer=above follow=on border=off
bspc rule -a copyq state=floating manage=on layer=above follow=on
bspc rule -a qbittorrent state=floating manage=on layer=above follow=on
bspc rule -a "Tor Browser" state=floating manage=on layer=above follow=on
bspc rule -a Nitrogen state=floating manage=on layer=above follow=on
bspc rule -a Peek state=floating manage=on layer=above follow=on border=off rectangle=1200x860
bspc rule -a Pavucontrol state=floating manage=on layer=above follow=on rectangle=717x739

