#!/bin/sh

# Set environment
export BSPWM_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/bspwm"

# Clear all rules:
bspc rule -r "*"

bspc monitor HDMI1 -d 1 2 3 4 5 8 10
bspc monitor eDP1 -d 6 7

# autostart

###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier mod4 # super key
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
# bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color	"4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#406ea5"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color "#dd2727"

###---Monitor And Desktop Settings----###
bspc config top_padding 24
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 4
bspc config window_gap 10

# Autostart
"$BSPWM_CONFIG/autostart" &

# Dektops:
bspc monitor --reset-desktops primary plan code browse conf media chat 8 9 10

# Window rules:
bspc rule -a albert state=floating manage=on layer=above border=off center
bspc rule -a MEGAsync state=floating manage=on layer=above follow=on border=off
bspc rule -a copyq state=floating manage=on layer=above follow=on
bspc rule -a qbittorrent state=floating manage=on layer=above follow=on
bspc rule -a "Tor Browser" state=floating manage=on layer=above follow=on
bspc rule -a Nitrogen state=floating manage=on layer=above follow=on
bspc rule -a Peek state=floating manage=on layer=above follow=on border=off rectangle=1200x860
bspc rule -a Pavucontrol state=floating manage=on layer=above follow=on rectangle=717x739
bspc rule -a dropdown_todo state=floating manage=on layer=above follow=on rectangle=1200x700

