#!/bin/sh

# Set environment
export BSPWM_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/bspwm"

# Clear all rules:
bspc rule -r "*"

bspc monitor HDMI1 -d 1 2 3 4 5 6 7
bspc monitor eDP1 -d 8

# autostart

###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier mod4 # super key
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
# bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color	"4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#406ea5"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color "#dd2727"

###---Monitor And Desktop Settings----###
bspc config top_padding 10
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 4
bspc config window_gap 10

# Dektops:
bspc monitor --reset-desktops primary plan code conf media chats 7

# Window rules:
bspc rule -a albert state=floating layer=above border=off follow=on focus=on center=true
bspc rule -a MEGAsync state=floating border=off
bspc rule -a copyq state=floating layer=above follow=on focus=on
bspc rule -a qBittorrent state=floating hidden=on center=true sticky=on follow=on
bspc rule -a "Tor Browser" state=floating layer=above
bspc rule -a Nitrogen state=floating layer=above
bspc rule -a Peek state=floating layer=above border=off rectangle=1200x860 follow=on focus=on
bspc rule -a Pavucontrol state=floating layer=above rectangle=717x739 follow=on focus=on
bspc rule -a dropdown_todo state=floating layer=above rectangle=1200x700
bspc rule -a TelegramDesktop desktop="chats" 
bspc rule -a tuijam state=floating layer=above rectangle=800x600
bspc rule -a ktouch state=floating layer=above rectangle=1000x700
bspc rule -a 'polkit-gnome-authentication-agent-1*:Polkit-gnome-authentication-agent-1*' rectangle=600x211 state=floating
bspc rule -a Gnome-calculator state=floating border=off sticky=on
bspc rule -a Anki state=floating rectangle=400x600 center=true
bspc rule -a Anki:* state=floating rectangle=800x400
bspc rule -a Enpass state=floating center=true rectangle=600x400 follow=on sticky=on
bspc rule -a spotify state=floating center=true rectangle=600x400 follow=on sticky=on
bspc rule -a Youtube-dl-gui state=floating center=true rectangle=600x400 follow=on
bspc rule -a Zathura:* state=floating layer=above rectangle=1200x1400
bspc rule -a mindfulness-at-the-computer.py state=floating

# Autostart
"$BSPWM_CONFIG/autostart" &

